spring:
  application:
    name: websockat

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}  # Hibernate ?? DDL ?? ??

    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true  # SQL ?? ??? ?? - ???? ????? ??, ?? ???? ??
        use_sql_comments: true  # SQL ?? ?? ?? ?? - ??, ?? ??, (???? JPQL? ? ? ??.)

server:
  port: ${SERVER_PORT}